version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./include/nginx/conf.d/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory # Test certs
    depends_on:
      - nginx
  
  ghost:
    image: ghost:4.13-alpine
    restart: always
    environment:
      - VIRTUAL_HOST=${DOMAIN},www.${DOMAIN}
      - VIRTUAL_PORT=2368
      - LETSENCRYPT_HOST=${DOMAIN},www.${DOMAIN}
      - url=https://${DOMAIN}
    volumes:
      - ./data/ghost:/var/lib/ghost/content

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs: